spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minishop
    username: postgres
    password: Munmun@171
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: false
server:
  port: 8885

payment:
  gateway:
    endpoint: http://localhost:8081/mock-pay

jwt:
  secret: change-this-secret-to-a-strong-one
  issuer: example-issuer
  validity-seconds: 3600

kafka:
  bootstrap-servers: localhost:9092
  topic:
    order-status: order-status-updates

security:
  idempotency-header: X-Idempotency-Key
